package udev

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"hidpass/internal/model"
)

const Header = "# Generated by hidpass. Do not edit; edit /etc/hidpass/devices.json via hidpass.\n"

func Generate(devices []model.AllowedDevice) ([]byte, error) {
	copyOf := append([]model.AllowedDevice(nil), devices...)
	for i := range copyOf {
		vid, pid, err := model.NormalizePair(copyOf[i].VID, copyOf[i].PID)
		if err != nil {
			return nil, fmt.Errorf("device %d: %w", i, err)
		}
		copyOf[i].VID, copyOf[i].PID = vid, pid
	}
	sort.Slice(copyOf, func(i, j int) bool { return copyOf[i].ID() < copyOf[j].ID() })
	var b bytes.Buffer
	b.WriteString(Header)
	b.WriteString("# Grants the active local seat user access; never grants global mode 0666.\n")
	for _, d := range copyOf {
		if d.Name != "" {
			fmt.Fprintf(&b, "# %s [%s]\n", safeComment(d.Name), safeComment(d.Category))
		}
		fmt.Fprintf(&b, "KERNEL==\"hidraw*\", ATTRS{idVendor}==\"%s\", ATTRS{idProduct}==\"%s\", TAG+=\"uaccess\"\n", d.VID, d.PID)
	}
	return b.Bytes(), nil
}

func safeComment(s string) string {
	return strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' || r == 0 {
			return ' '
		}
		return r
	}, s)
}

type Manager struct {
	RulesPath string
	Run       func(name string, args ...string) ([]byte, error)
}

func DefaultManager() Manager {
	return Manager{RulesPath: "/etc/udev/rules.d/70-hidpass.rules", Run: func(name string, args ...string) ([]byte, error) {
		return exec.Command(name, args...).CombinedOutput()
	}}
}

func (m Manager) Write(devices []model.AllowedDevice) error {
	b, err := Generate(devices)
	if err != nil {
		return err
	}
	dir := filepath.Dir(m.RulesPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create udev rules directory %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, ".70-hidpass.rules.*")
	if err != nil {
		return fmt.Errorf("create temporary rules file: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err = tmp.Chmod(0644); err == nil {
		_, err = tmp.Write(b)
	}
	if err == nil {
		err = tmp.Sync()
	}
	if closeErr := tmp.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return fmt.Errorf("write rules: %w", err)
	}
	if err := os.Rename(tmpName, m.RulesPath); err != nil {
		return fmt.Errorf("install rules %s: %w", m.RulesPath, err)
	}
	return nil
}

func (m Manager) Reload() error {
	if m.Run == nil {
		return fmt.Errorf("udev command runner is nil")
	}
	// Trigger only hidraw: a bare `udevadm trigger` re-emits uevents for every
	// device on the system, which is needlessly disruptive on a desktop.
	for _, args := range [][]string{{"control", "--reload-rules"}, {"trigger", "--subsystem-match=hidraw"}} {
		out, err := m.Run("udevadm", args...)
		if err != nil {
			return fmt.Errorf("udevadm %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
		}
	}
	return nil
}
